name: Secret Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check if FTP_PASS is set
        run: |
          if [ -z "${{ secrets.FTP_PASS }}" ]; then
            echo "FTP_PASS is empty or not set"
            exit 1
          else
            echo "FTP_PASS is set"
          fi
